;  external declarations for all procedures in NBASMC.LIB

.external argcv
.external capsoff
.external capson
.external delay
.external nosound
.external numoff
.external numon
.external getsinte
.external isalpha
.external isalt
.external iscntrl
.external islower
.external isupper
.external tolower
.external toupper
.external beep
.external blink
.external cursoff
.external curson
.external getvseg
.external iscolor
.external isega
.external graph
.external prtbin
.external prthex
.external prthexh
.external prthexn
.external prthexnh
.external prtint
.external prtoct
.external prtsint
.external prtstring
.external rand
.external sound
.external fdfree
.external fdtadata
.external frewind
.external ltrim
.external rtrim

.end
